base_model: mii-llm/Qwen-5588
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: True
load_in_8bit: false
load_in_4bit: true
strict: false

rl: dpo
datasets:
  - path: mii-llm/propaganda_dx_mix
    split: train
    type: chatml.intel
  
dataset_prepared_path: propaganda-dpo-dx
val_set_size: 0.0
output_dir: ./propaganda-dpo-dx

sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: Propaganda
wandb_entity: mii-llm
wandb_watch:
wandb_name: Propaganda-dx-01
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 5e-5

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

save_safetensors: true
ddp_timeout: 14400

warmup_steps: 100
evals_per_epoch: 15
saves_per_epoch: 10
save_total_limit: 3
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:

auto_resume_from_checkpoints: true

special_tokens:
  # pad_token: "<|endoftext|>"
  eos_token: "<|im_end|>"
